
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"


zstyle ':prezto:module:tmux:auto-start' 'yes'
alias l="eza -1a"
alias ls='eza --icons'
alias ll='ls -ahl'
alias cat='bat --style=plain'
k=kubectl

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

autoload -U +X bashcompinit && bashcompinit
autoload -U +X compinit && compinit

# AWS
# complete -C '/opt/homebrew/bin/aws_completer' aws

# Go-lang
export GOPATH=~/go
export GOBIN=${GOPATH//://bin:}/bin
export PATH=$PATH:$GOBIN
export GOPRIVATE=github.com/flowcommerce
go env -w GO111MODULE=auto

# flow
export HOMEBREW_GITHUB_API_TOKEN=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

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
